### ISSUE TITLE
space-tab-mix-disabled

### ISSUE THREAD

**Issue by dawidk92** [yaniswang/HTMLHint#119]
"space-tab-mixed-disabled": "tab"

I have space after `<span>` inside `<p>` and htmlhint throws it as an warning. It's really annoying issue

![image](https://cloud.githubusercontent.com/assets/7023167/14141408/1cd9f5e8-f67f-11e5-89e3-80a8db542206.png)

**Comment by shaochuancs** [comment]
Currently, "space-tab-mixed-disabled" rule in HTMLHint checks space/tab inside each DOM node, that's why the space after span tag will result in warning, when this rule value is "tab".

It seems this rule would be more reasonable if it only checks space/tab at the beginning of each line to alert bad indentation styles, and leave space/tab inside DOM element alone.

Need @yaniswang to confirm this behaviour change. I tried to fix this issue by fire new event when line break is found, but this may break some current design.

**Comment by molant** [comment]
In my case I'm solving this changing line 19 of space-tab-mixed-disabled.js with this:
```js
else if (options === 'tab' && /^\t+$/.test(match[2]) === false && match.input.indexOf('\n') !== -1) {
```
If there isn't a new line in the original string that I'm matching, then I ignore the error

**Comment by shaochuancs** [comment]
@molant, this is a quick fix and it solves the problem. However, the performance can be improved as space-tab-mixed-disabled rule does not need to be invoked if there is no line break.

I'll submit a pull request later, fixing this issue by fire&listen line-break event.
